/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.evolabs.estateagent;

/**
 *
 * @author silol
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        lblLocation = new javax.swing.JLabel();
        lblAgentName = new javax.swing.JLabel();
        lblPropertyPrice = new javax.swing.JLabel();
        lblCommission = new javax.swing.JLabel();
        cmbLocation = new javax.swing.JComboBox<>();
        txtAgentName = new javax.swing.JTextField();
        txtPropertyPrice = new javax.swing.JTextField();
        txtCommission = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReport = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuExitItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuProcessItem = new javax.swing.JMenuItem();
        menuClearItem = new javax.swing.JMenuItem();
        menuSaveItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLocation.setText("AGENT LOCATION:");

        lblAgentName.setText("ESTATE AGENT NAME:");

        lblPropertyPrice.setText("PROPERTY PRICE:");

        lblCommission.setText("COMMISSION PERCENTAGE:");

        cmbLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Location--", "Capetown", "Durban", "Pretoria" }));
        cmbLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLocationActionPerformed(evt);
            }
        });

        txtAgentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgentNameActionPerformed(evt);
            }
        });

        txtReport.setEditable(false);
        txtReport.setColumns(20);
        txtReport.setRows(5);
        jScrollPane1.setViewportView(txtReport);

        jMenu1.setText("File");

        menuExitItem.setText("Exit");
        menuExitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitItemActionPerformed(evt);
            }
        });
        jMenu1.add(menuExitItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");

        menuProcessItem.setText("Process Report");
        menuProcessItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcessItemActionPerformed(evt);
            }
        });
        jMenu2.add(menuProcessItem);

        menuClearItem.setText("Clear");
        menuClearItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClearItemActionPerformed(evt);
            }
        });
        jMenu2.add(menuClearItem);

        menuSaveItem.setText("Save Report");
        menuSaveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveItemActionPerformed(evt);
            }
        });
        jMenu2.add(menuSaveItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAgentName, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCommission)
                                    .addComponent(lblPropertyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPropertyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCommission, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(76, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocation)
                    .addComponent(cmbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentName)
                    .addComponent(txtAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropertyPrice)
                    .addComponent(txtPropertyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommission)
                    .addComponent(txtCommission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLocationActionPerformed

    private void txtAgentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgentNameActionPerformed

    private void menuExitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_menuExitItemActionPerformed

    private void menuClearItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClearItemActionPerformed
        // TODO add your handling code here:
        cmbLocation.setSelectedIndex(0);
txtAgentName.setText("");
txtPropertyPrice.setText("");
txtCommission.setText("");
txtReport.setText("");

    }//GEN-LAST:event_menuClearItemActionPerformed

    private void menuProcessItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcessItemActionPerformed
// 1. Get user input
String location = (String) cmbLocation.getSelectedItem();
String agentName = txtAgentName.getText().trim();
String priceText = txtPropertyPrice.getText().trim();
String commissionText = txtCommission.getText().trim();

// 2. Parse numbers safely
double propertyPrice;
double commissionPercentage;
try {
    propertyPrice = Double.parseDouble(priceText);
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Enter a valid number for Property Price.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}
try {
    commissionPercentage = Double.parseDouble(commissionText);
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Enter a valid number for Commission Percentage.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

// 3. Create data object
com.evolabs.estateagent.Data data = new com.evolabs.estateagent.Data(location, agentName, propertyPrice, commissionPercentage);

// 4. Logic object
com.evolabs.estateagent.EstateAgent logic = new com.evolabs.estateagent.EstateAgent();

// 5. Validate
boolean valid = logic.validateData(data);
if (!valid) {
    javax.swing.JOptionPane.showMessageDialog(this, "Validation failed. Ensure all fields are filled correctly.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

// 6. Generate report
String report = logic.generateReport(data);
txtReport.setText(report);
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuProcessItemActionPerformed

    private void menuSaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveItemActionPerformed
try (java.io.BufferedWriter writer = new java.io.BufferedWriter(new java.io.FileWriter("report.txt", false))) {
    writer.write(txtReport.getText());
    writer.flush();
    javax.swing.JOptionPane.showMessageDialog(this, "Report saved to report.txt", "Saved", javax.swing.JOptionPane.INFORMATION_MESSAGE);
} catch (java.io.IOException ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error saving file: " + ex.getMessage(), "File Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSaveItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbLocation;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgentName;
    private javax.swing.JLabel lblCommission;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblPropertyPrice;
    private javax.swing.JMenuItem menuClearItem;
    private javax.swing.JMenuItem menuExitItem;
    private javax.swing.JMenuItem menuProcessItem;
    private javax.swing.JMenuItem menuSaveItem;
    private javax.swing.JTextField txtAgentName;
    private javax.swing.JTextField txtCommission;
    private javax.swing.JTextField txtPropertyPrice;
    private javax.swing.JTextArea txtReport;
    // End of variables declaration//GEN-END:variables
}
